pipeline:
  build:
    image: plugins/docker
    repo: keymetrics/pm2-docs
    tags: 
      - latest
      - "${DRONE_COMMIT_SHA}"
    secrets: [ docker_username, docker_password ]
    when:
      event: push
      branch: [ master ]
  generate_pr:
    image: keymetrics/drone-plugin-auto-pr
    owner: keymetrics
    repository: infrastructure
    regex: 'keymetrics/pm2-docs:([A-Za-z0-9]+)'
    files:
      - 'jobs/frontend.nomad'
    message: 'chore: update pm2 doc job'
    secrets: [ github_oauth_token ]
    when:
      event: push
      branch: [ master ]
  slack:
    image: plugins/slack
    channel: dev-stream-ci
    when:
      event: push
      branch: [ master ]
      status: [ success, failure ]
    template: |
      {{#success build.status}}
        {{repo.name}} : {{build.event}} with commit {{truncate build.commit 8}} on branch "{{build.branch}}" done by {{build.author}} succeeded in {{since build.started}}
      {{else}}
        {{repo.name}} : {{build.event}} with commit {{truncate build.commit 8}} on branch "{{build.branch}}" done by {{build.author}} failed in {{since build.started}}
      {{/success}}
      see {{ build.link }}
    secrets: [ slack_webhook ]